os: linux
services:
    - docker
sudo: required
language: python
env:
    global:
        - CONAN_UPLOAD=1
        - CONAN_REFERENCE="log4cxx/0.10.0"
        - CONAN_USERNAME="vthiery"
        - CONAN_CHANNEL="stable"
        - CONAN_TOTAL_PAGES=1
        - CONAN_CURRENT_PAGE=1
        - CONAN_ARCHS="x86_64"

    matrix:
        - CONAN_GCC_VERSIONS=6.2 CONAN_USE_DOCKER=1

install:
    - ./.travis/install.sh
script:
    - ./.travis/run.sh